### ISSUE TITLE
2017 link in https://2018.makeorbreak.io/ is wrong

### ISSUE THREAD

**Issue by joaoportela** [makeorbreak-io/mob-web#145]
In https://2018.makeorbreak.io/ page the 2017 link at the bottom of the page points to https://2018.makeorbreak.io/ instead of https://2017.makeorbreak.io/

![image](https://user-images.githubusercontent.com/217176/80862156-b76cbc00-8c6a-11ea-97b9-a9798718d01b.png)

**Comment by hugopeixoto** [comment]
Thanks for noticing. The archive pages live in https://github.com/makeorbreak-io/web-archive, not on this repo. I'll submit a fix soon.

**Comment by hugopeixoto** [comment]
Fixed in https://github.com/makeorbreak-io/web-archive/pull/3
