### ISSUE TITLE
Normalize yes/no toggle switches

### ISSUE THREAD

**Issue by hugopeixoto** [makeorbreak-io/mob-web#67]
When going through the /welcome screen, I noticed that these switches sometimes show yes/no and other times no/yes. This should be consistent.

The reason they're like this may be that they have different default values. We should be careful to not change the default values.

![no-yes_000](https://user-images.githubusercontent.com/111554/66424524-b42b8d80-ea05-11e9-8015-eb64be6db79e.png)
![yes-no](https://user-images.githubusercontent.com/111554/66424525-b4c42400-ea05-11e9-9099-5a4b96d18779.png)

**Comment by StefanieJaeger** [comment]
I'll look into it
