### ISSUE TITLE
Fix "Hackahton" typo

### ISSUE THREAD

**Issue by hugopeixoto** [makeorbreak-io/mob-web#68]
There's a typo in the welcome page, where we spell Hackahton instead of Hackathon.

![typo](https://user-images.githubusercontent.com/111554/66424639-e9d07680-ea05-11e9-8873-3e33bdbaa6e0.png)

**Comment by Alireza-Sampour** [comment]
Hi @hugopeixoto , May i work on this?

**Comment by hugopeixoto** [comment]
@Alireza-Sampour yes, thanks for helping!

**Comment by Alireza-Sampour** [comment]
@hugopeixoto I've sent a PR for this

**Comment by hugopeixoto** [comment]
Merged & deployed. Thanks for contributing.
